Repository ButterFlight/butterflight, pull requests merged in 2018-04, with the labels that each got.

#109 quaternion sensor apply refactor
  src/main/drivers/accgyro/accgyro_imuf9001.c
  src/main/fc/config.c
  src/main/flight/imu.c
  src/main/interface/msp.c
  src/main/sensors/gyro.c
  src/main/target/HELIOSPRING/target.h
Labels: IMPROVEMENT, TESTING REQUIRED, enhancement

#117 updating default pids for yaw
  src/main/flight/pid.c
  src/main/target/HELIOSPRING/config.c
Labels: PRIORITIEZE, bug

#107 Omnibus F4 Fireworks Target
  src/main/target/OMNIBUSF4FW/config.c
  src/main/target/OMNIBUSF4FW/target.c
  src/main/target/OMNIBUSF4FW/target.h
  src/main/target/OMNIBUSF4FW/target.mk
Labels: Release Candidate
